#include "beep.h"
uint8_t song[][2] = {
    {NOTE_Dsharp, 5},
    {NOTE_F, 5},
    {NOTE_Fsharp, 5},
    {NOTE_Gsharp, 5},
    {NOTE_Asharp, 5},
    {NOTE_NONE, 5},

    {NOTE_Dsharp, 6},
    {NOTE_Csharp, 6},
    {NOTE_Asharp, 5},
    {NOTE_NONE, 5},
    {NOTE_Dsharp, 5},
    {NOTE_NONE, 5},

    {NOTE_Asharp, 5},
    {NOTE_Gsharp, 5},
    {NOTE_Fsharp, 5},
    {NOTE_F, 5},
    {NOTE_Dsharp, 5},
    {NOTE_F, 5},
    {NOTE_Fsharp, 5},
    {NOTE_Gsharp, 5},
    {NOTE_Asharp, 5},
    {NOTE_NONE, 5},

    {NOTE_Gsharp, 5},
    {NOTE_Fsharp, 5},
    {NOTE_F, 5},
    {NOTE_Dsharp, 5},
    {NOTE_F, 5},
    {NOTE_Fsharp, 5},
    {NOTE_F, 5},
    {NOTE_Dsharp, 5},
    {NOTE_D, 5},
    {NOTE_F, 5},

    {NOTE_Dsharp, 5},
    {NOTE_F, 5},
    {NOTE_Fsharp, 5},
    {NOTE_Gsharp, 5},
    {NOTE_Asharp, 5},
    {NOTE_NONE, 5},

    {NOTE_Dsharp, 6},
    {NOTE_Csharp, 6},
    {NOTE_Asharp, 5},
    {NOTE_NONE, 5},
    {NOTE_Dsharp, 5},
    {NOTE_NONE, 5},

    {NOTE_Asharp, 5},
    {NOTE_Gsharp, 5},
    {NOTE_Fsharp, 5},
    {NOTE_F, 5},
    {NOTE_Dsharp, 5},
    {NOTE_F, 5},
    {NOTE_Fsharp, 5},
    {NOTE_Gsharp, 5},
    {NOTE_Asharp, 5},
    {NOTE_NONE, 5},

    {NOTE_Gsharp, 5},
    {NOTE_Fsharp, 5},
    {NOTE_F, 5},
    {NOTE_NONE, 5},
    {NOTE_Fsharp, 5},
    {NOTE_NONE, 5},
    {NOTE_Gsharp, 5},
    {NOTE_NONE, 5},
    {NOTE_Asharp, 5},
    {NOTE_NONE, 5},

    {NOTE_Csharp, 6},
    {NOTE_Dsharp, 6},
    {NOTE_Asharp, 5},
    {NOTE_Gsharp, 5},
    {NOTE_Asharp, 5},
    {NOTE_NONE, 5},

    {NOTE_Gsharp, 5},
    {NOTE_Asharp, 5},
    {NOTE_Csharp, 6},
    {NOTE_Dsharp, 6},
    {NOTE_Asharp, 5},
    {NOTE_Gsharp, 5},
    {NOTE_Asharp, 5},
    {NOTE_NONE, 5},

    {NOTE_Gsharp, 5},
    {NOTE_Asharp, 5},
    {NOTE_Gsharp, 5},
    {NOTE_Fsharp, 5},
    {NOTE_F, 5},
    {NOTE_Csharp, 5},
    {NOTE_Dsharp, 5},
    {NOTE_NONE, 5},

    {NOTE_Csharp, 5},
    {NOTE_Dsharp, 5},
    {NOTE_F, 5},
    {NOTE_Fsharp, 5},
    {NOTE_Gsharp, 5},
    {NOTE_Asharp, 5},
    {NOTE_Dsharp, 5},
    {NOTE_NONE, 5},

    {NOTE_Asharp, 5},
    {NOTE_Csharp, 6},
    {NOTE_Csharp, 6},
    {NOTE_Dsharp, 6},
    {NOTE_Asharp, 5},
    {NOTE_Gsharp, 5},
    {NOTE_Asharp, 5},
    {NOTE_NONE, 5},

    {NOTE_Gsharp, 5},
    {NOTE_Asharp, 5},
    {NOTE_Csharp, 6},
    {NOTE_Dsharp, 6},
    {NOTE_Asharp, 5},
    {NOTE_Gsharp, 5},
    {NOTE_Asharp, 5},
    {NOTE_NONE, 5},

    {NOTE_Dsharp, 6},
    {NOTE_F, 6},
    {NOTE_Fsharp, 6},
    {NOTE_F, 6},
    {NOTE_Dsharp, 6},
    {NOTE_Csharp, 6},
    {NOTE_Asharp, 5},
    {NOTE_NONE, 5},

    {NOTE_Gsharp, 5},
    {NOTE_Asharp, 5},
    {NOTE_Gsharp, 5},
    {NOTE_Fsharp, 5},
    {NOTE_F, 5},
    {NOTE_Csharp, 5},
    {NOTE_Dsharp, 5},
    {NOTE_NONE, 5},
};


//∞¥º¸“Ù 4÷÷“Ù–ß
uint8_t kEY_VOL[][2] = {
	    {NOTE_Asharp, 5},
			{NOTE_G, 5},
	    {NOTE_Csharp, 5},
	    {NOTE_Fsharp, 5},			
};